[package]
name = "lumen-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Lumen - shared identifiers, hashing (BLAKE3), Ed25519 crypto wrappers, errors and time types"
keywords.workspace = true
categories.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
serde = { workspace = true }
elib-blake.workspace = true
elib-ed25519.workspace = true
elib-rng.workspace = true
elib-constant-time.workspace = true
elib-zeroize.workspace = true
hex.workspace = true
postcard.workspace = true

[dev-dependencies]
serde_json = { workspace = true }
